export const PREPARE_SIGNUP_REQUEST = "PREPARE_SIGNUP_REQUEST";
export const COMPLETE_SIGNUP_REQUEST = "COMPLETE_SIGNUP_REQUEST";
export const SET_TOKEN = "SET_TOKEN";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_ITEM_QUANTITY = "UPDATE_ITEM_QUANTITY";
export const UPDATE_CART_TOTAL = "UPDATE_CART_TOTAL";
export const PREPARE_ORDER_REQUEST = "PREPARE_ORDER_REQUEST";
export const COMPLETE_ORDER_REQUEST = "COMPLETE_ORDER_REQUEST";

export const GET_ORDERS = "GET_ORDERS";
export const GET_USER_ORDERS = "GET_USER_ORDERS";
export const MAKE_ORDER = "MAKE_ORDER";